import type { Preferences, RecorderState } from "./types";
export const defaultPreferences: Preferences = {
   collection: "",
   clipSeconds: 60,
   shortcut: "CommandOrControl+Shift+F8",
   quality: "standard",
   customWidth: 1920,
   customHeight: 1080,
   customFPS: 60,
   customCQ: 23,
   allowSoftwareEncoder: false,
   sourceKind: "screen",
   sourceId: "",
   microphone: false,
   microphoneDevice: "default",
   captureAudio: true,
   captureVolume: 1,
   captureMuted: false,
   microphoneVolume: 1,
   microphoneMuted: false,
   desktopFallback: false,
   shareSizeMB: 20,
   autoShare: false,
   startWithOS: false,
   autoRecord: false,
   notifications: "everywhere",
   sound: true,
   avoidOverlap: false,
   folderLayout: "flat",
   filenamePreset: "source-date",
   filenameTemplate: "{source} {date} {time}",
   setupComplete: false,
};
export const stoppedRecorder: RecorderState = {
   state: "stopped",
   startedAt: null,
   availableSeconds: 0,
   message: "",
   backend: "libOBS",
   supported: false,
   pendingSaves: 0,
};
